# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pr:
  autoCancel: true
  branches:
    include:
    - development

jobs:
  - job: CUDA_Build_Test
    pool: avatar
    timeoutInMinutes: 120
    steps:
    - task: CMake@1
      displayName: 'Configure CMake'
      inputs:
        cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release -DAMReX_SPACEDIM=3 -DAMReX_GPU_BACKEND=CUDA -DQUOKKA_PYTHON=OFF'
    
    - task: CMake@1
      displayName: 'Build Quokka'
      inputs:
        cmakeArgs: '--build . --parallel 16'
    
    - task: CMake@1
      displayName: 'Run CTest'
      inputs:
        cmakeArgs: '-E chdir . ctest -E "MatterEnergyExchange*" -T Test --output-on-failure'
    
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: cTest
        testResultsFiles: build/Testing/*/Test.xml
        testRunTitle: $(Agent.JobName)
      condition: succeededOrFailed()
      displayName: Publish test results
