name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-clang-tidy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - uses: ZedThree/clang-tidy-review@v0.19.0
      id: review
      with:
        config_file: src/.clang-tidy
        build_dir: build
        apt_packages: libopenmpi-dev,libhdf5-mpi-dev,python3-dev,python3-numpy,python3-matplotlib
        cmake_command: cmake . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DQUOKKA_PYTHON=ON -DQUOKKA_OPENPMD=ON -DopenPMD_USE_ADIOS2=OFF -DAMReX_SPACEDIM=3
        split_workflow: true

    # Uploads an artefact containing clang_fixes.json
    - uses: ZedThree/clang-tidy-review/upload@v0.19.0

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
